
const CONFIG = {"slug": "police", "version": "1.0.0", "title": "GENEVIEVE Police Safety & Operational Coordination™", "short": "Police Command", "descriptor": "Connected officer, incident, custody, community, asset and evidence safety", "roles": ["Duty officer", "Communications operator", "Patrol supervisor", "General duties officer", "Investigator", "Custody supervisor", "Intelligence officer", "Welfare and peer support lead", "Incident controller", "Governance reviewer"], "views": [["command", "Operational Command"], ["incidents", "Incidents & Calls"], ["officers", "Officer Safety"], ["custody", "Custody & Transport"], ["community", "Community & Vulnerable People"], ["assets", "Vehicles & Equipment"], ["handover", "Handover & Briefing"], ["evidence", "Evidence Timeline"], ["readiness", "Deployment Readiness"]], "modules": ["Call ownership and accepted tasking", "Officer location and welfare check-ins", "Scene hazard and withdrawal controls", "Custody, property and transport continuity", "Vulnerable-person and welfare-check routing", "Interagency request and accepted handover", "Vehicle, radio, body-worn camera and PPE readiness", "Evidence integrity and append-only incident history", "Fatigue, duress and post-incident support"], "sample": [["POL-204", "Welfare check requires authorised supervisor review", "RED", "Duty Inspector", "Patrol Supervisor", "12 min"], ["POL-311", "Custody transfer awaiting receiving acceptance", "AMBER", "Custody Supervisor", "Duty Officer", "24 min"], ["POL-088", "Radio fault reported by mobile unit", "AMBER", "Fleet & Comms", "Patrol Supervisor", "31 min"]], "assets": ["Marked vehicle 12", "Portable radio set B", "Body-worn camera pool", "Custody transport van", "Duress alert network"], "locations": ["North patrol sector", "Central watch-house", "Community response hub", "Major incident staging area"], "boundary": "The dashboard does not determine guilt, use of force, arrest, entry, pursuit, intelligence action, operational tactics or welfare-check outcome. Authorised police retain every decision."};
const $=s=>document.querySelector(s), content=$('#content'), titleEl=$('#title'), toast=$('#toast');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=`genevieve-${CONFIG.slug}-demo-v1`;
const stages=['GREEN','AMBER','RED','CRITICAL','GOVERNANCE'];
const now=()=>new Date().toISOString();
function seed(){return {incidents:CONFIG.sample.map((x,i)=>({id:x[0],title:x[1],stage:x[2],owner:x[3],backup:x[4],due:x[5],status:'OPEN',accepted:false,evidence:[],createdAt:now()})),audit:[{at:now(),action:'CONTROLLED DEMO OPENED',by:'System',detail:'Fictional data loaded; no real agency connection.'}],readiness:{roles:false,procedures:false,privacy:false,security:false,integration:false,training:false,testing:false,approval:false}}}
let state=loadState();
function loadState(){try{return JSON.parse(localStorage.getItem(key))||seed()}catch{return seed()}}
function save(){localStorage.setItem(key,JSON.stringify(state))}
function log(action,detail,by='Demo operator'){state.audit.unshift({at:now(),action,detail,by});save()}
function show(msg){toast.textContent=msg;toast.hidden=false;setTimeout(()=>toast.hidden=true,2500)}
function stage(x){return `<span class="stage ${esc(x)}">${esc(x)}</span>`}
function metric(a,b,c){return `<article class="card"><small>${esc(a)}</small><div class="metric">${esc(b)}</div><p>${esc(c)}</p></article>`}
function table(rows,heads,row){return `<div class="table-wrap"><table><thead><tr>${heads.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row).join('')}</tbody></table></div>`}
function counts(){const open=state.incidents.filter(x=>x.status!=='CLOSED');return {open:open.length,red:open.filter(x=>['RED','CRITICAL','GOVERNANCE'].includes(x.stage)).length,unaccepted:open.filter(x=>!x.accepted).length,evidence:open.reduce((a,x)=>a+x.evidence.length,0)}}
function command(){const c=counts();titleEl.textContent=CONFIG.views[0][1];content.innerHTML=`<div class="notice red"><b>Controlled working demonstration:</b> fictional or coded data only. It does not connect to an agency, dispatch service, operational network or emergency line.</div><div class="grid">${metric('Open matters',c.open,'Named primary and backup owners')}${metric('Red or higher',c.red,'Immediate authorised review')}${metric('Unaccepted',c.unaccepted,'Timed escalation remains active')}${metric('Evidence entries',c.evidence,'Append-only action history')}</div><article class="card"><h2>Priority queue</h2>${incidentTable(state.incidents.filter(x=>x.status!=='CLOSED'))}</article><article class="card"><h2>GENEVIEVE Accountability Core</h2><div class="tag-grid">${stages.map(x=>`<span>${x}</span>`).join('')}</div><p>An alert cannot close because it was seen or messaged. Ownership must be accepted, action evidence recorded, outcome documented and an authorised governance sign-off applied.</p></article>`}
function incidentTable(rows){if(!rows.length)return '<div class="empty">No open demo matters.</div>';return table(rows,['Matter','Owner / backup','Due','Stage','Status','Actions'],x=>`<tr><td><b>${esc(x.id)} — ${esc(x.title)}</b><br><span class="small">Created ${new Date(x.createdAt).toLocaleString('en-AU')}</span></td><td>${esc(x.owner)}<br><span class="small">Backup: ${esc(x.backup)}</span></td><td>${esc(x.due)}</td><td>${stage(x.stage)}</td><td>${x.accepted?'ACCEPTED':'UNACCEPTED'}<br>${esc(x.status)}</td><td><div class="actions"><button data-act="accept" data-id="${esc(x.id)}">Accept</button><button data-act="advance" data-id="${esc(x.id)}">Escalate</button><button data-act="evidence" data-id="${esc(x.id)}">Add evidence</button><button data-act="close" data-id="${esc(x.id)}">Close</button></div></td></tr>`) }
function incidents(){titleEl.textContent=CONFIG.views[1][1];content.innerHTML=`<div class="grid"><article class="card"><h2>Create fictional matter</h2><form id="newIncident" class="form"><label>Summary<input name="summary" required placeholder="Describe the operational safety matter"></label><label>Primary owner<select name="owner">${CONFIG.roles.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>Backup owner<select name="backup">${CONFIG.roles.slice().reverse().map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>Starting stage<select name="stage">${stages.map(x=>`<option>${x}</option>`).join('')}</select></label><button class="primary">Create matter</button></form></article><article class="card"><h2>Human decision boundary</h2><p>${esc(CONFIG.boundary)}</p><div class="notice"><b>Evidence rule:</b> record objective facts, actions and authorised decisions. Do not automatically label or blame a person.</div></article></div><article class="card"><h2>All matters</h2>${incidentTable(state.incidents)}</article>`}
function generic(viewName){titleEl.textContent=viewName;let body=''; if(/Personnel|Officer|Responder|Crew|Patrol/.test(viewName)){body=`<div class="grid">${CONFIG.roles.map((r,i)=>metric(r,i%3===0?'AVAILABLE':i%3===1?'ASSIGNED':'CHECK-IN DUE',i%3===2?'Backup owner notified':'Fictional roster status')).join('')}</div>`} else if(/Asset|Vehicle|Equipment|System/.test(viewName)){body=`<div class="grid">${CONFIG.assets.map((a,i)=>metric(a,i%4===0?'AMBER':'GREEN',i%4===0?'Evidence or service check due':'Fictional readiness recorded')).join('')}</div>`} else if(/Handover|Briefing/.test(viewName)){body=`<article class="card"><h2>Mandatory handover</h2><div class="tag-grid">${['Unresolved incidents','Changed hazards','Personnel and welfare','Assets blocked or degraded','External agency requests','Decisions awaiting acceptance','Next review times'].map(x=>`<span>${x}</span>`).join('')}</div><p>The receiving person must expressly accept each unresolved responsibility. A sent message is not an accepted handover.</p></article>${incidentTable(state.incidents.filter(x=>x.status!=='CLOSED'))}` } else {body=`<div class="grid">${CONFIG.modules.map((m,i)=>metric(m,i%5===0?'REVIEW':i%4===0?'AMBER':'ACTIVE','Named owner, backup, due time and evidence')).join('')}</div><article class="card"><h2>Operational locations</h2><div class="tag-grid">${CONFIG.locations.map(x=>`<span>${x}</span>`).join('')}</div></article>`} content.innerHTML=`<div class="notice"><b>Human-led safety:</b> ${esc(CONFIG.boundary)}</div>${body}`}
function evidence(){titleEl.textContent='Evidence Timeline';content.innerHTML=`<div class="notice"><b>Append-only demo history:</b> reset creates a new demo dataset; normal actions add entries rather than rewriting history.</div><article class="card"><div class="actions"><button id="exportJson">Export JSON</button><button id="exportCsv">Export CSV</button></div></article><article class="card"><h2>Audit entries</h2><div class="audit">${state.audit.map(x=>`<div class="entry"><b>${esc(x.action)}</b> — ${esc(x.detail)}<br><span class="small">${new Date(x.at).toLocaleString('en-AU')} · ${esc(x.by)}</span></div>`).join('')}</div></article>`}
function readiness(){titleEl.textContent='Deployment Readiness';const names={roles:'Agency roles and permissions approved',procedures:'Current procedures and escalation approved',privacy:'Privacy and data handling approved',security:'Cybersecurity and access controls approved',integration:'Authorised system integrations tested',training:'User training and competency completed',testing:'Field, accessibility and recovery testing completed',approval:'Written agency release authority recorded'};content.innerHTML=`<div class="notice red"><b>Production fails closed:</b> every gate must be approved by the relevant organisation. This demonstration is not operational authority.</div><article class="card"><h2>Release gates</h2><div class="form">${Object.entries(names).map(([k,v])=>`<label><input type="checkbox" data-ready="${k}" ${state.readiness[k]?'checked':''}> ${esc(v)}</label>`).join('')}</div></article>`}
const funcs={command,incidents,evidence,readiness};
function activate(name){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const item=CONFIG.views.find(x=>x[0]===name);(funcs[name]||(()=>generic(item?item[1]:name)))();history.replaceState(null,'',`#${name}`)}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.addEventListener('submit',e=>{if(e.target.id==='newIncident'){e.preventDefault();const fd=new FormData(e.target);const id=`${CONFIG.slug.toUpperCase().slice(0,3)}-${String(Date.now()).slice(-5)}`;state.incidents.unshift({id,title:fd.get('summary'),owner:fd.get('owner'),backup:fd.get('backup'),stage:fd.get('stage'),due:'New',status:'OPEN',accepted:false,evidence:[],createdAt:now()});log('MATTER CREATED',`${id}: ${fd.get('summary')}`);show('Fictional matter created');incidents()}})
document.addEventListener('change',e=>{if(e.target.dataset.ready){state.readiness[e.target.dataset.ready]=e.target.checked;log('READINESS GATE CHANGED',`${e.target.dataset.ready}: ${e.target.checked?'approved in demo':'not approved'}`);show('Readiness updated')}})
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)return activate(b.dataset.view);const x=b.dataset.id&&state.incidents.find(i=>i.id===b.dataset.id);if(b.dataset.act&&x){if(b.dataset.act==='accept'){x.accepted=true;log('OWNERSHIP ACCEPTED',x.id)}if(b.dataset.act==='advance'){const i=Math.min(stages.length-1,stages.indexOf(x.stage)+1);x.stage=stages[i];log('MATTER ESCALATED',`${x.id} to ${x.stage}`)}if(b.dataset.act==='evidence'){const detail=prompt('Enter objective action/evidence for this fictional matter:');if(detail){x.evidence.push({at:now(),detail});log('EVIDENCE ADDED',`${x.id}: ${detail}`)}}if(b.dataset.act==='close'){if(!x.accepted){show('Blocked: ownership must be accepted');return}if(!x.evidence.length){show('Blocked: action evidence is required');return}if(x.stage!=='GOVERNANCE'){show('Blocked: governance sign-off stage is required');return}x.status='CLOSED';log('MATTER CLOSED',`${x.id} after governance sign-off`)}save();show('Dashboard updated');activate(location.hash.slice(1)||'command')}if(b.id==='exportJson')download(`${CONFIG.slug}-audit.json`,JSON.stringify(state,null,2));if(b.id==='exportCsv'){const rows=[['time','action','by','detail'],...state.audit.map(x=>[x.at,x.action,x.by,x.detail])];download(`${CONFIG.slug}-audit.csv`,rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')}if(b.id==='resetDemo'){if(confirm('Reset fictional demo data?')){state=seed();save();show('Demo reset');activate('command')}}if(b.id==='refresh'){state=loadState();show('Dashboard refreshed');activate(location.hash.slice(1)||'command')}})
(function init(){document.querySelector('#productName').textContent=CONFIG.title;document.querySelector('#descriptor').textContent=CONFIG.descriptor;document.querySelector('#boundary').textContent=CONFIG.boundary;document.querySelector('nav').innerHTML=CONFIG.views.map((x,i)=>`<button data-view="${x[0]}" class="${i===0?'active':''}">${x[1]}</button>`).join('');activate(location.hash.slice(1)||CONFIG.views[0][0])})();
